sudo: false
language: node_js
node_js:
  - lts/*

cache:
  directories:
    - node_modules

install:
  - yarn

script:
  - yarn lint
  - yarn test

after_success:
  - bash <(curl -s https://codecov.io/bash)
